repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 7.1.2
  hooks:
    - id: flake8
- repo: https://github.com/PyCQA/pylint
  rev: v3.3.6
  hooks:
    - id: pylint
      additional_dependencies:
        - flask
        - flask-sqlalchemy
        - flask-login
        - flask-migrate
        - google-auth
        - google-auth-oauthlib
        - google-api-python-client
        - authlib
        - litellm
        - todoist-api-python
        - O365
        - msal
        - azure-identity
        - msgraph-sdk
        - pymysql
