repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
- repo: https://github.com/psf/black
  rev: 24.4.0
  hooks:
    - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
    - id: flake8
- repo: https://github.com/PyCQA/pylint
  rev: v3.1.0
  hooks:
    - id: pylint
      args:
        - --rcfile=.pylintrc
      additional_dependencies:
        - google-auth
        - google-auth-oauthlib
        - google-api-python-client
        - flask
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.0
  hooks:
    - id: poetry-install
      additional_dependencies: ["poetry>=1.8.2"]
