[tool.poetry]
name = "virtual-calendar-assistant"
version = "0.1.0"
description = "Virtual Calendar Assistant"
authors = ["Corrin Lakeland <lakeland@gmail.com>"]
license = "PRIVATE"
readme = "README.md"
include = ["**/pyproject.toml"]
package-mode = false


[tool.poetry.dependencies]
python = "^3.12"
openai = "*"
O365 = "*"
Flask = "*"
python-dotenv = "*"
httpx = "*"
google-api-python-client = "*"
google-auth-oauthlib = "*"
Jinja2 = "*"
Flask-SQLAlchemy = "*"
Authlib = "*"
flask-migrate = "*"
todoist-api-python = "*"
msal = "*"
flask-login = "*"

[tool.poetry.group.dev.dependencies]
flake8 = "*"
pylint = "*"
isort = "*"
black = "*"
pre-commit = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
