[tool.poetry]
name = "virtual-calendar-assistant"
version = "0.1.0"
description = "Virtual Calendar Assistant"
authors = ["Corrin Lakeland <lakeland@gmail.com>"]
license = "PRIVATE"
readme = "README.md"
include = ["**/pyproject.toml"]


[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.23.1"
O365 = "^2.0.34"
Flask = "^3.0.3"
python-dotenv = "^1.0.1"
httpx = "^0.27.0"
google-api-python-client ="^2.124.0"
google-auth-oauthlib = "^1.2.0"
Jinja2 = "^3.1.3"
Flask-SQLAlchemy = "^3.1.1"
Authlib = "^1.3.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
pylint = "^3.1.0"
isort = "^5.13.2"
black = "^24.4.0"
pre-commit = "^3.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

package-mode = false
