"""Initial migration with consolidated schema

Revision ID: 1dbca46bc9be
Revises: 
Create Date: 2026-03-07 18:47:36.412827

"""
from alembic import op
import sqlalchemy as sa
from virtual_assistant.database.user import MySQLUUID


# revision identifiers, used by Alembic.
revision = '1dbca46bc9be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', MySQLUUID(length=16), nullable=False),
    sa.Column('app_login', sa.String(length=120), nullable=False),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('openai_key', sa.Text(), nullable=True),
    sa.Column('ai_instructions', sa.Text(), nullable=True),
    sa.Column('schedule_slot_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_app_login'), ['app_login'], unique=True)

    op.create_table('external_account',
    sa.Column('id', MySQLUUID(length=16), nullable=False),
    sa.Column('external_email', sa.String(length=255), nullable=False),
    sa.Column('user_id', MySQLUUID(length=16), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_uri', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('is_primary_calendar', sa.Boolean(), nullable=True),
    sa.Column('is_primary_tasks', sa.Boolean(), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('needs_reauth', sa.Boolean(), nullable=False),
    sa.Column('use_for_calendar', sa.Boolean(), nullable=False),
    sa.Column('use_for_tasks', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', MySQLUUID(length=16), nullable=False),
    sa.Column('user_id', MySQLUUID(length=16), nullable=False),
    sa.Column('task_user_email', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_task_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.String(length=255), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.String(length=255), nullable=True),
    sa.Column('section_id', sa.String(length=255), nullable=True),
    sa.Column('list_type', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_user_email', 'provider', 'provider_task_id', name='uq_user_id_task_user_provider_task')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_task_user_email'), ['task_user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_task_user_email'))

    op.drop_table('tasks')
    op.drop_table('external_account')
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_app_login'))

    op.drop_table('app_user')
    # ### end Alembic commands ###
