"""Add llm_model column to user

Revision ID: 1f3226b41e1b
Revises: aa922a3945d8
Create Date: 2026-03-07 21:11:23.321982

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1f3226b41e1b"
down_revision = "aa922a3945d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("llm_model", sa.String(length=100), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_user", schema=None) as batch_op:
        batch_op.drop_column("llm_model")

    # ### end Alembic commands ###
