"""Add schedule_slot_duration to user model

Revision ID: 460449018edf
Revises: d48024de5506
Create Date: 2025-04-13 20:42:45.512115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460449018edf'
down_revision = 'd48024de5506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_slot_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('schedule_slot_duration')

    # ### end Alembic commands ###
