"""initial_migration_with_uuid_ids

Revision ID: 8ddb0a51cf89
Revises: 
Create Date: 2025-04-13 14:34:33.635604

"""
from alembic import op
import sqlalchemy as sa
import virtual_assistant.database.user


# revision identifiers, used by Alembic.
revision = '8ddb0a51cf89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', virtual_assistant.database.user.MySQLUUID(length=16), nullable=False),
    sa.Column('app_login', sa.String(length=120), nullable=False),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('openai_key', sa.Text(), nullable=True),
    sa.Column('grok_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_app_login'), ['app_login'], unique=True)

    op.create_table('calendar_account',
    sa.Column('id', virtual_assistant.database.user.MySQLUUID(length=16), nullable=False),
    sa.Column('calendar_email', sa.String(length=255), nullable=False),
    sa.Column('user_id', virtual_assistant.database.user.MySQLUUID(length=16), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_uri', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('needs_reauth', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'calendar_email', 'provider', name='uq_calendar_account_user_id_provider')
    )
    op.create_table('task_accounts',
    sa.Column('id', virtual_assistant.database.user.MySQLUUID(length=16), nullable=False),
    sa.Column('user_id', virtual_assistant.database.user.MySQLUUID(length=16), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('task_user_email', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('needs_reauth', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_name', 'task_user_email', name='uq_user_provider_email')
    )
    with op.batch_alter_table('task_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_accounts_provider_name'), ['provider_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_accounts_task_user_email'), ['task_user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', virtual_assistant.database.user.MySQLUUID(length=16), nullable=False),
    sa.Column('user_id', virtual_assistant.database.user.MySQLUUID(length=16), nullable=False),
    sa.Column('task_user_email', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_task_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.String(length=255), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.String(length=255), nullable=True),
    sa.Column('section_id', sa.String(length=255), nullable=True),
    sa.Column('list_type', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_user_email', 'provider', 'provider_task_id', name='uq_user_id_task_user_provider_task')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_task_user_email'), ['task_user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_task_user_email'))

    op.drop_table('tasks')
    with op.batch_alter_table('task_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_accounts_task_user_email'))
        batch_op.drop_index(batch_op.f('ix_task_accounts_provider_name'))

    op.drop_table('task_accounts')
    op.drop_table('calendar_account')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_app_login'))

    op.drop_table('user')
    # ### end Alembic commands ###
