"""Add conversation and chat_message tables

Revision ID: aa922a3945d8
Revises: 1dbca46bc9be
Create Date: 2026-03-07 20:56:29.759130

"""
from alembic import op
import sqlalchemy as sa
from virtual_assistant.database.user import MySQLUUID


# revision identifiers, used by Alembic.
revision = 'aa922a3945d8'
down_revision = '1dbca46bc9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', MySQLUUID(length=16), nullable=False),
    sa.Column('user_id', MySQLUUID(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', MySQLUUID(length=16), nullable=False),
    sa.Column('conversation_id', MySQLUUID(length=16), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=255), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    op.drop_table('conversation')
    # ### end Alembic commands ###
