"""add_user_id_foreign_key_to_calendar_account

Revision ID: d661bc6e8631
Revises: add_app_user_email_column
Create Date: 2025-02-28 21:44:57.945018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd661bc6e8631'
down_revision = 'add_app_user_email_column'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_account', schema=None) as batch_op:
        batch_op.alter_column('calendar_email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('refresh_token',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('token_uri',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('client_secret',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('scopes',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint('_email_provider_uc', type_='unique')
        batch_op.create_unique_constraint('_calendar_email_provider_uc', ['calendar_email', 'provider'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_account', schema=None) as batch_op:
        batch_op.drop_constraint('_calendar_email_provider_uc', type_='unique')
        batch_op.create_unique_constraint('_email_provider_uc', ['calendar_email', 'provider'])
        batch_op.alter_column('scopes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
        batch_op.alter_column('client_secret',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('token_uri',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('refresh_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
        batch_op.alter_column('token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=False)
        batch_op.alter_column('calendar_email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
