"""Add is_primary flag to TaskAccount

Revision ID: f9a48064d88e
Revises: e3f0ffa1011c
Create Date: 2025-04-12 22:07:16.594778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a48064d88e'
down_revision = 'e3f0ffa1011c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_accounts', schema=None) as batch_op:
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###
